- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/logcache_tls?/private_key
  value: "((cc_logcache_tls.private_key))"

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/logcache_tls?/certificate
  value: "((cc_logcache_tls.certificate))"

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/logcache_tls?/ca_cert
  value: "((cc_logcache_tls.ca))"

- type: replace
  path: /variables/name=cc_logcache_tls?
  value:
    name: cc_logcache_tls
    type: certificate
    options:
      ca: "((log_cache.ca))"
      common_name: "api.ink-whale.capi.land"
      alternative_names:
      - "api.ink-whale.capi.land"
      - cloud-controller-ng.service.cf.internal

#/bosh-lite/cf/cc_logcache_tls
